<?php

function sfafeeds_block($op = 'list', $delta = 0) {
  $block = array();

  switch ($op) {
    case 'list' :
      $block[0]['info'] = t('SFA Feeds');
      break;
    case 'view' :
      $block_content = t('We Are SFA!');
      $block["subject"] = t('This is Content!');
      $block["content"] = $block_content;
      break;
  }
  return $block;
}

function sfafeeds_cron(){
    drupal_set_message(t(" SFA HELP "));

}
